# Generated by Django 5.0.7 on 2024-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('js', 'JavaScript'), ('HTML', 'html'), ('cpp', 'C++'), ('py', 'Python')], max_length=30),
        ),
    ]
